### ISSUE TITLE
[compat] settings need updating

### ISSUE THREAD

**Issue by JeffreySarnoff** [chriselrod/SLEEFPirates.jl#1]
Please consider updating these or else allowing range of versions (while you may wish to constrain versions more tightly, e.g. `julia = "1"` allows 1.0.0, 1.3.1 etc.)
```
[compat]
SIMDPirates = "0.1.5"
VectorizationBase = "0.1.9"
julia = "1.0.0"
```
Exact versions get out of date quickly and cause e.g.
```
ERROR: Unsatisfiable requirements detected for package VectorizationBase [3d5dd08c]:
 VectorizationBase [3d5dd08c] log:
 ├─possible versions are: 0.1.0-0.1.9 or uninstalled
 ├─restricted to versions 0.1.9-0.1 by SLEEFPirates [476501e8], leaving only versions 0.1.9
 │ └─SLEEFPirates [476501e8] log:
 │   ├─possible versions are: 0.1.3 or uninstalled
 │   └─SLEEFPirates [476501e8] is fixed to version 0.1.3
 └─restricted to versions 0.1.10-0.1 by SIMDPirates [21efa798] — no versions left
   └─SIMDPirates [21efa798] log:
     ├─possible versions are: 0.1.7 or uninstalled
     ├─restricted to versions 0.1.5-0.1 by SLEEFPirates [476501e8], leaving only versions 0.1.7
     │ └─SLEEFPirates [476501e8] log: see above
     └─SIMDPirates [21efa798] is fixed to version 0.1.7
```

**Comment by chriselrod** [comment]
Your error:
```
 ├─possible versions are: 0.1.0-0.1.9 or uninstalled
 ├─restricted to versions 0.1.9-0.1 by SLEEFPirates
...
└─restricted to versions 0.1.10-0.1 by SIMDPirates
```

From [the documentation](https://julialang.github.io/Pkg.jl/v1/compatibility/):
> Caret specifiers are the default and hence `1.2.3 == ^1.2.3`.
> `PkgD = "^0.2.3" # [0.2.3, 0.3.0)`

So, if I understand the documentation correctly, specifying `0.1.9` should allow for `[0.1.9, 0.2.0)`. Which includes `0.1.10`.

In clear contradiction of your error, unless I'm misunderstanding something.

Should I just set the upper bounds to infinity (also wrong, but probably less so in practice)?
```julia
[compat]
SIMDPirates = ">= 0.1.5"
VectorizationBase = ">= 0.1.9"
julia = "1.0.0"
```
Or maybe writing out the caret `^` would help?
?

EDIT: I also find that I need to constantly keep the Manifests up to date, as Julia will sometimes look to that and error if it conflicts with a `[compat]`.

**Comment by JeffreySarnoff** [comment]
I think it comes down to "[for pre-1.0 versions] When the minor version is not zero, versions with the same minor versions are considered compatible, i.e. the two versions 0.2.1 and 0.2.3 are considered compatible" as I understand it version 0.2.1 is not considered compatible with 0.3.0, even though version 1.2.1 is considered compatible with version 1.3.0. 

Just adding a carat to versions specified with three numbers may not do it: 
"PkgD = "^0.2.3" # [0.2.3, 0.3.0)"

In part to avoid dealing with updating manifests (and mostly because it has worked thus far), I use lines like `SIMDPirates = "0"`, which covers releases until version 1.0.0, and I want to be forced to revisit compatibilities at that point. 

For pkgs with versions like 0.#.#, using the `>=` (more open-ended) or using `= "0"` (less open-ended)` seem to _play-well-with-others_.  Some explicit guidance in the docs would help.

**Comment by chriselrod** [comment]
Okay, I'll set them all to `SIMDPirates = ">="`. I really do want to set lower bounds.

I'm currently working on an internal rework of LoopVectorization which I'll push out at the same time as these changes; some of its dependencies need changes to support that rework, so I plan on pushing all the updates at about the same time, and tagging new commits for each then.

I'll try and do this ASAP, staying up tonight if I have to (although I'll sleep if I'm still not done by the time I get off work tomorrow).

**Comment by chriselrod** [comment]
SLEEFPirates isn't really tied to and shouldn't be dependent on those other changes, so I went ahead and added the `">="` and tagged a new version.

Please let me know if you run into any more problems.

**Comment by chriselrod** [comment]
No upper bound causes problems for automerging:
https://github.com/JuliaRegistries/General/pull/8180

That means I either need a specific version, or to have no lower bound?

**Comment by JeffreySarnoff** [comment]
I forgot about [this new requirement for automerging](https://github.com/JuliaRegistries/General/pull/8180#issuecomment-576103760).  Now the system wants an upperbound on the [compat] entries.

**Comment by JeffreySarnoff** [comment]
It means that you can use any bounded range of versions (either implicitly bounded `julia = "1"` or explicitly bounded `julia = 1.0, 1.1, 1.2, 1.3, 1.4, 1.5`)

**Comment by chriselrod** [comment]
Yeah, I guess I should follow this example:
```
[compat]
Example = "1.2, 2" # = [1.2.0, 3.0.0)
```
So I think I'll try this:
```
SIMDPirates = "0.1.5,0.2"
VectorizationBase = "0.1.9,0.2"
julia = "1"
```
which should be good for everything up until 0.3.

**Comment by JeffreySarnoff** [comment]
standing by, thank you for the attention to this

**Comment by chriselrod** [comment]
All checks have now passed for auto-merging, but the auto-merge message hasn't updated and still claims it will need manual review.
Hopefully it'll automerge anyway.

**Comment by JeffreySarnoff** [comment]
Close but .. I think you want
```
[compat]
SIMDPirates = "0.1, 0.2"
VectorizationBase = "0.1, 0.2"
julia = "1"
```
because specifying "0.1.5, 0.2" says 0.1.5 or 0.2.x (omitting 0.1.6 .. 0.1.9) .. the rules for versions that start with 0 are different than those that start with 1+.  "1.1.5, 1.2"  does cover 1.1.6.1.1.9.

you should update the versions in the [compat] sections of your other current pkgs,
VectorizationBase and SIMDPirates particularly for this kind of use by others.


fyi
```
ERROR: Unsatisfiable requirements detected for package VectorizationBase [3d5dd08c]:
 VectorizationBase [3d5dd08c] log:
 ├─possible versions are: 0.1.0-0.1.9 or uninstalled
 ├─restricted to versions 0.1.9-0.2 by SLEEFPirates [476501e8], leaving only versions 0.1.9
 │ └─SLEEFPirates [476501e8] log:
 │   ├─possible versions are: 0.1.4 or uninstalled
 │   └─SLEEFPirates [476501e8] is fixed to version 0.1.4
 └─restricted to versions 0.1.10-0.1 by SIMDPirates [21efa798] — no versions left
   └─SIMDPirates [21efa798] log:
     ├─possible versions are: 0.1.7 or uninstalled
     ├─restricted to versions 0.1.5-0.2 by SLEEFPirates [476501e8], leaving only versions 0.1.7
     │ └─SLEEFPirates [476501e8] log: see above
     └─SIMDPirates [21efa798] is fixed to version 0.1.7
```

**Comment by JeffreySarnoff** [comment]
I sent you PRs that adjust [compat] entries and bump the last number in the pkg version.
SIMDPirates should be updated before SLEEFPirates then VectorizationBase before LoopVectorization. 
What I did is what I use -- to see it done more narrowly: https://github.com/JuliaGizmos/GtkReactive.jl/blob/master/Project.toml

**Comment by chriselrod** [comment]
I don't like the lack of lower bounds. They really did depend on the lower bounds I gave.
I'll accept these for now (acknowledging that people could easily get errors if the package manager will not update).

I'll bump VectorizationBase/SIMDPirates/SLEEFPirates to 0.2 and LoopVectorization to 0.4, and set all the dependencies to "= 0.2".

**Comment by chriselrod** [comment]
I'm closing this for now, because I think this may have been related:
https://github.com/JuliaLang/Pkg.jl/issues/1694#issuecomment-590106680
Because the package server was out of sync, it didn't yet offer 0.1.10, causing the error you reported.

Please let me know if you experience any more problems.
