### ISSUE TITLE
Docs links not working

### ISSUE THREAD

**Issue by cossio** [chriselrod/SLEEFPirates.jl#10]
The docs link on the README do not seem to work. Update them?

**Comment by chriselrod** [comment]
I need to add docs.

**Comment by ViralBShah** [comment]
While the links in the README do not work - I found it easy to find the docs on JuliaHub. https://juliahub.com/docs/SLEEFPirates/EjaJG/0.5.4/

**Comment by chriselrod** [comment]
There's not much in terms of documentation, but the links work.
