### ISSUE TITLE
Add `DOCUMENTER_KEY` for deploying the docs with GitHub Actions

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/SLEEFPirates.jl#15]
Now that CI has been moved to GitHub Actions, we need to add a new Documenter deploy key.

@chriselrod Can you do the following?

Step 1:
```julia
julia> import Pkg
julia> Pkg.add("DocumenterTools")
julia> import DocumenterTools
julia> DocumenterTools.genkeys()
```

Step 2: Go to https://github.com/chriselrod/SLEEFPirates.jl/settings/secrets/actions. Create a new GitHub Secret with name `DOCUMENTER_KEY` where the value is the Base64-encoded private key from step 1.

Step 3: Go to https://github.com/chriselrod/SLEEFPirates.jl/settings/keys. Create a new deploy key with name `DOCUMENTER_KEY_PUBLIC` where the value is the public key from step 1. Make sure that the deploy key has write access.

**Comment by DilumAluthge** [comment]
@chriselrod I have bad news for you. You'll need to repeat these three steps for every single repository that is now running on GitHub Actions.

**Comment by chriselrod** [comment]
Thanks, I've enabled it for VectorizationBase, SLEEFPirates, LoopVectorization, VectorizedRNG, PaddedMatrices, and a few others.
