### ISSUE TITLE
Method overwrite warning on SLEEFPirates v0.6.1

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/SLEEFPirates.jl#16]
> WARNING: Method definition integer2float(Type{Float64}, VectorizationBase.AbstractSIMD{W, Int32}) where {W} in module SLEEFPirates at /home/runner/.julia/packages/SLEEFPirates/RgmaT/src/utils.jl:41 overwritten at /home/runner/.julia/packages/SLEEFPirates/RgmaT/src/utils.jl:44.
>   ** incremental compilation may be fatally broken for this module **

This is with SLEEFPirates v0.6.1 on Julia 1.5.3.

Example log: https://github.com/DilumAluthge/Augustus.jl/pull/3/checks?check_run_id=1612274763

**Comment by chriselrod** [comment]
Thanks for the issue. Not sure what my original intention was with those two definitions.
For now, I made one specific to `Int32` and the other to `Int64`.

When I fix the broken tests on Julia master, I'll also test on a 32-bit build of Julia to make sure that's okay Then it'd be good to also enable tests for 32-bit.
